### ISSUE TITLE
Arm without delay

### ISSUE THREAD

**Issue by kpdillon** [bryanbartow/homebridge-alarm.com#31] opened 2016-10-13 14:25 UTC
There seems to be no way to arm the alarm in away mode without delay.  In other words when arming at night there should be away to arm the alarm and check no delay so that if an intruder walks in through a door the alarm sounds immediately.

**Comment by bryanbartow** [comment] 2016-10-13 17:38
That's what the "Arm Stay" mode is, right? In HomeKit it's referred to as Night mode. Am I missing something?

**Comment by kpdillon** [comment] 2016-10-13 18:06
So in my testing, 

Home - bypasses inside motions
Away - arms all but there is a 30 second delay before the alarm goes off if triggered
Night - Same behavior as away

I would expect Night to turn on the alarm with no 30 second delay.  On the alarm.com app there is an option to set away with "no delay".

**Comment by bryanbartow** [comment] 2016-10-13 18:24
Unfortunately, we're limited to the options available on the Alarm.com mobile site, which are Disarm, Arm Stay and Arm Away. Unless someone is able to reverse engineer the API the mobile app is using, we're stuck.

**Comment by kpdillon** [comment] 2016-10-13 18:26
So the option has to be available in alarm.com/pda right?  Think they would add it if I asked them?  Would that help?

**Comment by bryanbartow** [comment] 2016-10-13 18:36
The WrapAPI calls are manipulating alarm.com/pda, so, yes, the feature would have to be available there first before we could consider implementing it. I'm closing this for now. We can reopen it if/when it's possible.

**Closed as completed by bryanbartow** 2016-10-13 18:36 UTC
Labels: duplicate

**Comment by amitgandhinz** [comment] 2016-10-13 18:42
fwiw I'm using the Night Mode which arms stay without any delay.

**Comment by kpdillon** [comment] 2016-10-13 18:46
Just to clarify - it arms without any delay, however when someone opens a sensor (like a door) the alarm system gives you 30 seconds to disable instead of tripping right away.  In the alarm.com app you can enable the alarm and check "no delay" which will trigger the alarm immediately without the 30 seconds to disable.

**Comment by amitgandhinz** [comment] 2016-10-13 19:12
ah thanks for the clarification - i have not tested that yet

**Comment by bryanbartow** [comment] 2016-10-13 19:46
Just realized this is a duplicate of #24
